### ISSUE TITLE
Can we have a `replicated-channel` (optional) input param?

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/action-kots-release#1]
This workflow works to create a release and promote it to a new branch-named channel.
```yaml
      - name: Create the release
        uses: replicatedhq/action-kots-release@v0.2.0
        with:
          replicated-app: "my-app"
          replicated-api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          yaml-dir: ./kots          
```

But I'd like to do something specific in my app, such as:
- When it's the master branch, promote to beta.
- When it's the release branch, promote to stable

What about (this is aspirational yaml, not does not work):

```yaml
      - name: Create the release
        if: github.ref == 'refs/head/master'
        uses: replicatedhq/action-kots-release@v0.2.0
        with:
          replicated-app: "my-app"
          replicated-api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          replicated-channel: "Beta"
          yaml-dir: ./kots          
```
